import logging
import json
import os
from datetime import datetime, timedelta
from typing import List, Optional

from dotenv import load_dotenv
from livekit.agents import (
    Agent,
    AgentSession,
    JobContext,
    JobProcess,
    MetricsCollectedEvent,
    RoomInputOptions,
    WorkerOptions,
    cli,
    metrics,
    tokenize,
    function_tool,
    RunContext
)
from livekit.plugins import murf, silero, google, deepgram, noise_cancellation
from livekit.plugins.turn_detector.multilingual import MultilingualModel

logger = logging.getLogger("agent")

load_dotenv(".env.local")

DB_PATH = "wellness_log.json"

def load_history():
    if not os.path.exists(DB_PATH):
        return []
    try:
        with open(DB_PATH, "r") as f:
            return json.load(f)
    except Exception:
        return []

def get_context_prompt():
    history = load_history()
    if not history:
        return "This is your first session with the user."
    
    last_entry = history[-1]
    # Parse timestamp for friendlier display if needed, but ISO is okay for LLM to understand
    return f"""
    Last session was on {last_entry.get('timestamp')}.
    User's mood was: {last_entry.get('mood')}.
    Their objectives were: {', '.join(last_entry.get('objectives', []))}.
    Start by referencing this briefly (e.g., "Last time you mentioned...").
    """

class WellnessCompanion(Agent):
    def __init__(self) -> None:
        context_str = get_context_prompt()
        super().__init__(
            instructions=f"""You are a supportive, grounded Health & Wellness Voice Companion.
            Your goal is to have a short daily check-in with the user.
            
            CONTEXT FROM PREVIOUS SESSION:
            {context_str}

            FLOW:
            1. **Greeting & Context**: Welcome them. If there's history, mention it briefly to show continuity.
            2. **Mood Check**: Ask how they are feeling or what their energy is like.
            3. **Objectives**: Ask for 1-3 simple goals/intentions for today.
            4. **Advice**: Offer ONE piece of simple, grounded, non-medical advice based on what they said.
            5. **Recap & Confirm**: Summarize their mood and objectives. Ask "Does this sound right?"
            6. **Save**: Once confirmed, IMMEDIATELY call the `save_checkin` tool.
            7. **Goodbye**: Wish them well and end the conversation.

            GUIDELINES:
            - Be empathetic but realistic.
            - NO medical diagnosis or advice.
            - Keep responses concise (spoken conversation).
            - If the user changes their mind, update your understanding before saving.
            """,
        )

    @function_tool
    async def save_checkin(
        self, 
        context: RunContext, 
        mood: str, 
        objectives: List[str], 
        summary: str
    ):
        """Save the daily check-in details to the log file. Call this ONLY after the user confirms the recap.
        
        Args:
            mood: The user's self-reported mood or energy level.
            objectives: A list of 1-3 goals or intentions the user stated.
            summary: A one-sentence summary of the session generated by you.
        """
        # Mocking date for challenge purposes: each new session is "the next day"
        history = load_history()
        mock_date = datetime.now() + timedelta(days=len(history))

        entry = {
            "timestamp": mock_date.isoformat(),
            "mood": mood,
            "objectives": objectives,
            "summary": summary
        }
        
        history.append(entry)
        
        try:
            with open(DB_PATH, "w") as f:
                json.dump(history, f, indent=2)
            logger.info(f"Saved check-in: {entry}")
            return "Check-in saved successfully. You can now say goodbye."
        except Exception as e:
            logger.error(f"Failed to save check-in: {e}")
            return f"Error saving check-in: {e}"

def prewarm(proc: JobProcess):
    proc.userdata["vad"] = silero.VAD.load()

async def entrypoint(ctx: JobContext):
    # Logging setup
    ctx.log_context_fields = {
        "room": ctx.room.name,
    }

    session = AgentSession(
        stt=deepgram.STT(model="nova-3"),
        llm=google.LLM(
                model="gemini-2.5-flash",
            ),
        tts=murf.TTS(
                voice="en-US-matthew", 
                style="Conversation",
                tokenizer=tokenize.basic.SentenceTokenizer(min_sentence_len=2),
                text_pacing=True
            ),
        turn_detection=MultilingualModel(),
        vad=ctx.proc.userdata["vad"],
        preemptive_generation=True,
    )

    usage_collector = metrics.UsageCollector()

    @session.on("metrics_collected")
    def _on_metrics_collected(ev: MetricsCollectedEvent):
        metrics.log_metrics(ev.metrics)
        usage_collector.collect(ev.metrics)

    async def log_usage():
        summary = usage_collector.get_summary()
        logger.info(f"Usage: {summary}")

    ctx.add_shutdown_callback(log_usage)

    await session.start(
        agent=WellnessCompanion(),
        room=ctx.room,
        room_input_options=RoomInputOptions(
            noise_cancellation=noise_cancellation.BVC(),
        ),
    )

    await ctx.connect()


if __name__ == "__main__":
    cli.run_app(WorkerOptions(entrypoint_fnc=entrypoint, prewarm_fnc=prewarm))